@HostAddress = https://localhost:7168/api
@ViewerToken = J3PkxKv8YvwUMK8uaZY6cQ==
@CoordinatorToken = G7gYZqy3nHpraJ9FCCfoBQ==
@AdministratorToken = Kh5O/naBc2cLy11qucBpsg==

POST {{HostAddress}}/management/room
Authorization: Bearer {{AdministratorToken}}
Accept: application/json
Content-Type: application/json

{
  "Name": "Sala 1",
  "Description": "Mesas em pé no segundo andar.",
  "Capacity": 4
}

####################################################################

POST {{HostAddress}}/management/room
Authorization: Bearer {{AdministratorToken}}
Accept: application/json
Content-Type: application/json

{
  "Name": "Sala 2",
  "Description": "Perto da saída com banheiro exclusivo.",
  "Capacity": 8
}

####################################################################

POST {{HostAddress}}/management/room
Authorization: Bearer {{AdministratorToken}}
Accept: application/json
Content-Type: application/json

{
  "Name": "Sala 3",
  "Description": "Ainda em construção.",
  "Capacity": 15
}

####################################################################

POST {{HostAddress}}/management/room
Authorization: Bearer {{AdministratorToken}}
Accept: application/json
Content-Type: application/json

{
  "Name": "Auditório",
  "Description": "Aconchegante e moderno.",
  "Capacity": 80
}