@platform_HostAddress = https://localhost:7168/api

GET {{platform_HostAddress}}/Setup/Startup
Accept: application/json

############################################################

GET {{platform_HostAddress}}/Setup/Startup/Logotype
Accept: application/json

############################################################

POST {{platform_HostAddress}}/Setup/Installation
Accept: application/json
Content-Type: application/json

{
  "Name": "ABC",
  "Logotype": "123"
}

############################################################

GET {{platform_HostAddress}}/Setup/Access
Accept: application/json


############################################################

GET {{platform_HostAddress}}/Setup/Authentication
Accept: application/json
password: ,FS2o<3}