@platform_HostAddress = https://localhost:7168/api

GET {{platform_HostAddress}}/setup/startup
Accept: application/json

############################################################

GET {{platform_HostAddress}}/setup/startup/logotype
Accept: application/json

############################################################

POST {{platform_HostAddress}}/setup/installation
Accept: application/json
Content-Type: application/json

{
  "Name": "ABC",
  "Logotype": "123"
}

############################################################

GET {{platform_HostAddress}}/setup/access
Accept: application/json


############################################################

GET {{platform_HostAddress}}/setup/authentication
Accept: application/json
password: ,FS2o<3}